version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/node:20.5.1
    working_directory: ~/teamspeak-server
    steps:
      - run:
          name: Checkout Repo
          command: git clone https://github.com/csongorhg/teamspeak-server.git && cd teamspeak-server
      - run:
          name: Install AWS CLI and Deploy Cloudformation
          command: |
            sudo apt-get update && sudo apt-get install -qq -y
            sudo apt-get install python3-dev
            curl -O https://bootstrap.pypa.io/pip/3.6/get-pip.py && sudo python get-pip.py
            sudo pip install -q awscli --upgrade
      - run: ./deploy.sh
